# Generated by Django 4.1.7 on 2023-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='fone',
            field=models.CharField(max_length=25, null=True, verbose_name='Telefone'),
        ),
    ]
