# Generated by Django 4.2 on 2023-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='telefone',
            new_name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='CEP',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fone_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacao',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
