# Generated by Django 4.2.4 on 2023-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customusuario_fone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuário'),
        ),
    ]
