# Generated by Django 4.2 on 2023-08-15 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tipoagregado_rename_telefone_fornecedor_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('nome', models.CharField(max_length=20, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pen_6_30_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_4_80_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_2_40_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_1_20_mm', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_600_um', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_300_um', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_150_um', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('pen_75_um', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('fundo', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('umidade', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('massa_especifica', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('is_deleted', models.BooleanField()),
                ('fk_usuario_id', models.IntegerField()),
                ('num_modificacao', models.IntegerField()),
            ],
        ),
    ]
