# Generated by Django 4.2 on 2023-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_agregado_fundo_alter_agregado_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado',
            name='num_modificacao',
            field=models.IntegerField(default=0),
        ),
    ]
