# Generated by Django 4.2 on 2023-08-16 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_historico_traco_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregado',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
