# Generated by Django 4.2 on 2023-08-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_agregado_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregado',
            name='data_cadastro',
        ),
    ]
