# Generated by Django 4.2 on 2023-08-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_agregado_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregado',
            name='fk_fornecedor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agregado',
            name='fk_tipo_agregado_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
