# Generated by Django 4.2 on 2023-08-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_agregado_fk_fornecedor_agregado_fk_tipo_agregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado',
            name='fk_tipo_agregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregados', to='usuarios.tipoagregado'),
        ),
    ]
