# Generated by Django 4.2 on 2023-08-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_agregado_fk_tipo_agregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado',
            name='fk_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.fornecedor'),
        ),
    ]
