# Generated by Django 4.2.4 on 2023-08-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_agregado_fk_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregado',
            name='fk_tipo_agregado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoagregado'),
        ),
    ]
