# Generated by Django 4.2.4 on 2023-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_agregado_fk_tipo_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='fone_2',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='agregado',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='CEP',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fone_1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='observacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoagregado',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
