# Generated by Django 4.2.4 on 2023-08-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_fornecedor_fone_2_alter_agregado_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoagregado',
            table='tipo_agregado',
        ),
    ]
