# Generated by Django 4.2.4 on 2023-08-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_tipoagregado_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agregado',
            table='agregado',
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor',
        ),
        migrations.AlterModelTable(
            name='traco',
            table='traco',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
