# Generated by Django 4.2 on 2023-08-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_agregado_table_alter_fornecedor_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traco',
            name='descricao',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traco',
            name='porcentagem_agua',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
