# Generated by Django 4.2.4 on 2023-08-31 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_fornecedor_data_cadastro_tipoagregado_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='observacao',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TracoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem', models.FloatField()),
                ('agregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agregado')),
                ('traco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.traco')),
            ],
            options={
                'db_table': 'traco_agregado',
            },
        ),
        migrations.AddField(
            model_name='traco',
            name='agregados',
            field=models.ManyToManyField(through='usuarios.TracoAgregado', to='usuarios.agregado'),
        ),
    ]
