# Generated by Django 4.2.4 on 2023-09-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_fornecedor_bairro_alter_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traco',
            name='agregados',
            field=models.ManyToManyField(blank=True, through='usuarios.TracoAgregado', to='usuarios.agregado'),
        ),
        migrations.AlterField(
            model_name='tracoagregado',
            name='agregado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.agregado'),
        ),
    ]
