# Generated by Django 4.2.5 on 2023-09-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_tracoagregado_traco'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracoagregado',
            unique_together={('traco', 'agregado')},
        ),
    ]
