# Generated by Django 4.2.5 on 2023-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_tracoagregado_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='login',
            field=models.CharField(default='2023-01-01', max_length=50, unique=True, verbose_name='Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='nome',
            field=models.CharField(default='ale', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusuario',
            name='permissao',
            field=models.CharField(default='teste', max_length=100, verbose_name='Permissão'),
            preserve_default=False,
        ),
    ]
