# Generated by Django 4.2.5 on 2023-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_customusuario_login_customusuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='login',
            field=models.CharField(max_length=50, verbose_name='Login'),
        ),
    ]
