# Generated by Django 4.2.4 on 2023-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_alter_customusuario_login'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agregado',
            unique_together={('id', 'num_modificacao')},
        ),
    ]
