# Generated by Django 4.2.4 on 2023-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_agregado_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agregado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agregado',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='agregado',
            unique_together={('id', 'num_modificacao', 'nome')},
        ),
    ]
