# Generated by Django 4.2.4 on 2023-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_alter_agregado_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agregado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agregado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agregado',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
