# Generated by Django 4.2.4 on 2023-09-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_alter_agregado_unique_together_alter_agregado_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoTraco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=10)),
                ('peso_final', models.FloatField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_traco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.traco')),
                ('fk_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
