# Generated by Django 4.2.4 on 2023-09-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_calculotraco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculotraco',
            old_name='fk_traco_id',
            new_name='fk_traco',
        ),
        migrations.RenameField(
            model_name='calculotraco',
            old_name='fk_usuario_id',
            new_name='fk_usuario',
        ),
    ]
