# Generated by Django 4.2.4 on 2023-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_rename_fk_traco_id_calculotraco_fk_traco_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calculotraco',
            table='calculo_traco',
        ),
    ]
