# Generated by Django 4.2.4 on 2023-09-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_alter_calculotraco_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregadosCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=15)),
                ('fk_agregado', models.ForeignKey(on_delete=models.SET(-1), to='usuarios.agregado')),
                ('fk_calculo_traco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.calculotraco')),
                ('tipo_agregado', models.ForeignKey(on_delete=models.SET(-1), to='usuarios.tipoagregado')),
            ],
            options={
                'db_table': 'agregados_calculo',
            },
        ),
    ]
