# Generated by Django 4.2.4 on 2023-09-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_agregadoscalculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregadoscalculo',
            name='fk_agregado',
        ),
    ]
