# Generated by Django 4.2.4 on 2023-09-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_remove_agregadoscalculo_fk_agregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregadoscalculo',
            name='tipo_agregado',
            field=models.CharField(max_length=50),
        ),
    ]
