# Generated by Django 4.2.4 on 2023-09-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_alter_agregadoscalculo_tipo_agregado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AlterModelOptions(
            name='customusuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='customusuario',
            table='usuarios',
        ),
    ]
